services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: spring-api-dev
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
    volumes:
      - ./api:/app
      - ~/.m2:/root/.m2
    command: mvn spring-boot:run
    restart: no
    healthcheck:
      test: ["CMD", "curl", "-v", "-f", "http://localhost:8080/api/actuator/health"]
      interval: 1s
      timeout: 5s
      retries: 10
      start_period: 10s

  ui:
    build:
      context: ./ui
      dockerfile: Dockerfile
    container_name: react-ui-dev
    ports:
      - "5173:5173"
    volumes:
      - ./ui:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
    command: sh -c "echo 'Waiting for backend...' && \
                   until curl -sf http://api:8080/api/actuator/health | grep '\"status\":\"UP\"'; do \
                     sleep 3; \
                   done && \
                   echo 'Backend is ready, starting UI...' && npm run dev"
    restart: no
    depends_on:
      api:
        condition: service_healthy
