services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: spring-api-dev
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
    volumes:
      - ./api:/app
      - ~/.m2:/root/.m2        # reuse local Maven cache for speed
    command: mvn spring-boot:run
    restart: no
  ui:
    build:
      context: ./ui
      dockerfile: Dockerfile
    container_name: react-ui-dev
    ports:
      - "5173:5173"
    volumes:
      - ./ui:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true   # for Linux Docker volume file changes
    command: npm run dev
    restart: no
    depends_on:
      - api
