services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: spring-api-dev
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
    volumes:
      - ./api:/app
      - ~/.m2:/root/.m2        # reuse local Maven cache for speed
    command: mvn spring-boot:run
    restart: no

